services:
  opensearch:
    build: ./opensearch
    container_name: opensearch_evals
    environment:
      discovery.type: single-node
      node.name: opensearch
      plugins.security.disabled: "true"
      logger.level: info
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: Evals_pa$$word_test0
    volumes:
      - /home/vishal/code/opensearch_eval/models:/models
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net

networks:
  opensearch-net:
    driver: bridge
